# Generated by Django 6.0.2 on 2026-03-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_inscripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneo',
            old_name='cupos',
            new_name='cupo_maximo',
        ),
    ]
