# Generated by Django 6.0.2 on 2026-03-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_rename_cupos_torneo_cupo_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='torneos/'),
        ),
    ]
