# Generated by Django 6.0.2 on 2026-03-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_torneo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='IMG/torneos/'),
        ),
    ]
