# Generated by Django 6.0.2 on 2026-03-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0005_alter_torneo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nombre_equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='numero_personas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='estado_reserva',
            field=models.CharField(choices=[('Abiertas', 'Abiertas'), ('Cerradas', 'Cerradas')], default='Abiertas', max_length=20),
        ),
        migrations.AddField(
            model_name='torneo',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='premio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='tipo_juego',
            field=models.CharField(blank=True, choices=[('Bolirana', 'Bolirana'), ('Rana', 'Rana'), ('Tejo', 'Tejo'), ('Billar', 'Billar')], max_length=50, null=True),
        ),
    ]
