# Generated by Django 6.0.2 on 2026-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0006_inscripcion_categoria_inscripcion_nombre_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='estado_reserva',
        ),
        migrations.AddField(
            model_name='torneo',
            name='valor_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='premio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
