# Generated by Django 6.0.2 on 2026-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0007_remove_torneo_estado_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
