# Generated by Django 6.0.2 on 2026-03-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0008_torneo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='pago',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
