# Generated by Django 6.0.2 on 2026-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0010_integrante'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='ganador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
