# Generated by Django 6.0.2 on 2026-03-25 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0011_torneo_ganador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_ganados', to='torneos.inscripcion'),
        ),
    ]
