# Generated by Django 6.0.2 on 2026-03-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0012_alter_torneo_ganador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='premio',
            field=models.CharField(max_length=100),
        ),
    ]
