# Generated by Django 6.0.2 on 2026-03-13 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_venta_detalleventa'),
        ('torneos', '0002_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torneos.torneo'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
