# Generated by Django 6.0.2 on 2026-03-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_venta_torneo_alter_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
